
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AbonosPersona
{

    public int IDAbonoPersona { get; set; }

    public int IDAbono { get; set; }

    public int IDPersona { get; set; }

    public decimal Cantidad { get; set; }

    public int UnidadDeMedida { get; set; }



    public virtual Abonos Abonos { get; set; }

    public virtual Personas Personas { get; set; }

}

}
