
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AccesoFormularioUsuario
{

    public int IdAccesoFormularioUsuario { get; set; }

    public int IdUsuario { get; set; }

    public Nullable<int> IdUsuarioAdicional { get; set; }

    public bool HomeValores { get; set; }

    public bool ComercialPedidoDeVenta { get; set; }

    public bool ComercialFacturaDeVenta { get; set; }

    public bool ComercialCobranzas { get; set; }

    public bool ComercialPresupuestos { get; set; }

    public bool ComercialAbonos { get; set; }

    public bool ComercialEntregas { get; set; }

    public bool ComercialProductosYServicios { get; set; }

    public bool ComercialClientes { get; set; }

    public bool SuministroPedidoDeCompra { get; set; }

    public bool SuministroComprobanteDeCompra { get; set; }

    public bool SuministroPagos { get; set; }

    public bool SuministroProveedores { get; set; }

    public bool AdministracionBancos { get; set; }

    public bool AdministracionInstituciones { get; set; }

    public bool AdministracionGastos { get; set; }

    public bool AdministracionMovimientos { get; set; }

    public bool AdministracionDetalleBancario { get; set; }

    public bool AdministracionCheques { get; set; }

    public bool AdministracionCaja { get; set; }

    public bool AdministracionCuentasCorrientes { get; set; }

    public bool AdministracionGastosGenerales { get; set; }

    public bool ProduccionMateriales { get; set; }

    public bool ProduccionAlmacenes { get; set; }

    public bool ProduccionCostos { get; set; }

    public bool ProduccionRecursos { get; set; }

    public bool ProduccionPlanificacion { get; set; }

    public bool PlaneamientoObjetivos { get; set; }

    public bool PlaneamientoProgramas { get; set; }

    public bool PlaneamientoPresupuestos { get; set; }

    public bool InfoFinancierosVentasVsCompras { get; set; }

    public bool InfoFinancierosComprasPorCategoria { get; set; }

    public bool InfoGananciasVsPerdidasCobradoVsPagado { get; set; }

    public bool InfoImpositivosIVAVentas { get; set; }

    public bool InfoImpositivosIVACompras { get; set; }

    public bool InfoImpositivosIVASaldo { get; set; }

    public bool InfoImpositivosRetenciones { get; set; }

    public bool InfoImpositivosPercepciones { get; set; }

    public bool InfoImpositivosCITIComprasYVentas { get; set; }

    public bool InfoGestionCuentaCorriente { get; set; }

    public bool InfoGestionCobranzaPendientes { get; set; }

    public bool InfoGestionPagoAProveedores { get; set; }

    public bool InfoGestionStockProductos { get; set; }

    public bool InfoGestionStockDetalle { get; set; }

    public bool InfoGestionCuentasAPagar { get; set; }

    public bool InfoGestionRankingPorCliente { get; set; }

    public bool InfoGestionRankingPorProductoServicio { get; set; }

    public bool InfoGestionTrackingHoras { get; set; }

    public bool InfoGestionListaFacturas { get; set; }

    public bool InfoGestionComisiones { get; set; }

    public bool HerramientasExploradorDeArchivos { get; set; }

    public bool HerramientasImportacionMasiva { get; set; }

    public bool HerramientasTrackingDeHoras { get; set; }

    public bool HerramientasConfigurarAlertas { get; set; }

    public bool HerramientasGeneracionCompraAutomatica { get; set; }

    public bool HerramientasGeneracionLiquidoProducto { get; set; }

    public bool HerramientasGeneracionFacturaAutomatica { get; set; }

    public bool HerramientasAuditoria { get; set; }

    public bool HabilitarCambioIvaEnArticulosDesdeComprobante { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
