
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Activos
{

    public int IDActivos { get; set; }

    public int IDPersona { get; set; }

    public int IDCompra { get; set; }

    public Nullable<System.DateTime> FechaInicioDeUso { get; set; }

    public Nullable<System.DateTime> FechaCompra { get; set; }

    public string Garantia { get; set; }

    public string VidaUtil { get; set; }

    public string Marca { get; set; }

    public string NumeroDeSerie { get; set; }

    public string Descripcion { get; set; }

    public string Responsable { get; set; }

    public string Ubicacion { get; set; }

    public string Observaciones { get; set; }



    public virtual Compras Compras { get; set; }

    public virtual Personas Personas { get; set; }

}

}
