
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Actividad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Actividad()
    {

        this.Comprobantes = new HashSet<Comprobantes>();

    }


    public int IdActividad { get; set; }

    public int IdUsuario { get; set; }

    public string Codigo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public Nullable<System.DateTime> FechaBaja { get; set; }

    public bool PorDefecto { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comprobantes> Comprobantes { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
