
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AlertasGeneradas
{

    public int IDAlertasGeneradas { get; set; }

    public int IDUsuario { get; set; }

    public int IDAlerta { get; set; }

    public int IDPersona { get; set; }

    public string NroComprobante { get; set; }

    public decimal ImportePagado { get; set; }

    public bool Visible { get; set; }

    public System.DateTime Fecha { get; set; }

    public Nullable<int> IDPagos { get; set; }

    public Nullable<int> IDCobranzas { get; set; }



    public virtual Alertas Alertas { get; set; }

    public virtual Cobranzas Cobranzas { get; set; }

    public virtual Pagos Pagos { get; set; }

    public virtual Personas Personas { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
