
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Alertas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Alertas()
    {

        this.AlertasGeneradas = new HashSet<AlertasGeneradas>();

    }


    public int IDAlerta { get; set; }

    public int IDUsuario { get; set; }

    public string AvisoAlerta { get; set; }

    public string Condicion { get; set; }

    public decimal Importe { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AlertasGeneradas> AlertasGeneradas { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
