
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Asientos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Asientos()
    {

        this.AsientoDetalle = new HashSet<AsientoDetalle>();

    }


    public int IDAsiento { get; set; }

    public int IDUsuario { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Leyenda { get; set; }

    public Nullable<int> IDCompra { get; set; }

    public Nullable<int> IDPago { get; set; }

    public Nullable<int> IDComprobante { get; set; }

    public Nullable<int> IDCobranza { get; set; }

    public Nullable<int> IDGastosBancarios { get; set; }

    public Nullable<int> IDCheque { get; set; }

    public bool EsAsientoCierre { get; set; }

    public bool EsAsientoInicio { get; set; }

    public Nullable<int> IDCaja { get; set; }

    public Nullable<int> IDMovimientoDeFondo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsientoDetalle> AsientoDetalle { get; set; }

    public virtual Cobranzas Cobranzas { get; set; }

    public virtual Compras Compras { get; set; }

    public virtual GastosBancarios GastosBancarios { get; set; }

    public virtual MovimientoDeFondos MovimientoDeFondos { get; set; }

    public virtual Pagos Pagos { get; set; }

    public virtual Comprobantes Comprobantes { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
