
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AsientoDetalle
{

    public int IDAsientoParte { get; set; }

    public int IDAsiento { get; set; }

    public int IDPlanDeCuenta { get; set; }

    public string TipoDeAsiento { get; set; }

    public decimal Importe { get; set; }

    public int Moneda { get; set; }



    public virtual Asientos Asientos { get; set; }

    public virtual PlanDeCuentas PlanDeCuentas { get; set; }

}

}
