
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AuditoriaDeCambio
{

    public int idRegistro { get; set; }

    public string ValorAnterior { get; set; }

    public string ValorNuevo { get; set; }

    public string Tabla { get; set; }

    public string Columna { get; set; }

    public string Objeto { get; set; }

    public string IdentificadorDeReferencia { get; set; }

    public int IdUsuario { get; set; }

    public System.DateTime Fecha { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
