
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AvisosVencimiento
{

    public int IDAvisosVencimientos { get; set; }

    public int IDUsuario { get; set; }

    public bool Activa { get; set; }

    public string TipoAlerta { get; set; }

    public string ModoDeEnvio { get; set; }

    public int CantDias { get; set; }

    public string Asunto { get; set; }

    public string Mensaje { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
