
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AvisosVencimientosView
{

    public int IDComprobante { get; set; }

    public System.DateTime FechaVencimiento { get; set; }

    public string Tipo { get; set; }

    public int Punto { get; set; }

    public int Numero { get; set; }

    public decimal Saldo { get; set; }

    public int IDPersona { get; set; }

    public string RazonSocialPersona { get; set; }

    public string EmailPersona { get; set; }

    public int IDUsuario { get; set; }

    public string RazonSocialUsuario { get; set; }

    public Nullable<int> IDPlan { get; set; }

    public string EmailUsuario { get; set; }

    public bool Activa { get; set; }

    public string TipoAlerta { get; set; }

    public string ModoDeEnvio { get; set; }

    public int CantDias { get; set; }

    public string Asunto { get; set; }

    public string Mensaje { get; set; }

}

}
