
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Bancos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Bancos()
    {

        this.BancosPlanDeCuenta = new HashSet<BancosPlanDeCuenta>();

        this.ChequeAccion = new HashSet<ChequeAccion>();

        this.CobranzasFormasDePago = new HashSet<CobranzasFormasDePago>();

        this.GastosBancarios = new HashSet<GastosBancarios>();

        this.MovimientoDeFondos = new HashSet<MovimientoDeFondos>();

        this.MovimientoDeFondos1 = new HashSet<MovimientoDeFondos>();

        this.PagosFormasDePago = new HashSet<PagosFormasDePago>();

    }


    public int IDBanco { get; set; }

    public int IDUsuario { get; set; }

    public string NroCuenta { get; set; }

    public string Moneda { get; set; }

    public bool Activo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public decimal SaldoInicial { get; set; }

    public int IDBancoBase { get; set; }

    public string Ejecutivo { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Observaciones { get; set; }

    public string AtributoDeSeguridad { get; set; }



    public virtual BancosBase BancosBase { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BancosPlanDeCuenta> BancosPlanDeCuenta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChequeAccion> ChequeAccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CobranzasFormasDePago> CobranzasFormasDePago { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GastosBancarios> GastosBancarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MovimientoDeFondos> MovimientoDeFondos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MovimientoDeFondos> MovimientoDeFondos1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PagosFormasDePago> PagosFormasDePago { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
