
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Compras
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Compras()
    {

        this.Activos = new HashSet<Activos>();

        this.Asientos = new HashSet<Asientos>();

        this.Jurisdicciones = new HashSet<Jurisdicciones>();

        this.PagosDetalle = new HashSet<PagosDetalle>();

    }


    public int IDCompra { get; set; }

    public int IDUsuario { get; set; }

    public Nullable<int> IDCategoria { get; set; }

    public int IDPersona { get; set; }

    public System.DateTime Fecha { get; set; }

    public decimal Importe2 { get; set; }

    public decimal Importe5 { get; set; }

    public decimal Importe10 { get; set; }

    public decimal Importe21 { get; set; }

    public decimal Importe27 { get; set; }

    public string Tipo { get; set; }

    public string NroFactura { get; set; }

    public decimal Redondeo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public string Observaciones { get; set; }

    public decimal Iva { get; set; }

    public decimal NoGravado { get; set; }

    public string Rubro { get; set; }

    public decimal ImporteMon { get; set; }

    public Nullable<decimal> Total { get; set; }

    public decimal Saldo { get; set; }

    public string Foto { get; set; }

    public decimal ImpNacional { get; set; }

    public decimal ImpMunicipal { get; set; }

    public decimal ImpInterno { get; set; }

    public decimal PercepcionIVA { get; set; }

    public decimal IIBB { get; set; }

    public decimal Otros { get; set; }

    public decimal Exento { get; set; }

    public Nullable<decimal> TotalImpuestos { get; set; }

    public System.DateTime FechaEmision { get; set; }

    public Nullable<int> IDPlanDeCuenta { get; set; }

    public System.DateTime FechaPrimerVencimiento { get; set; }

    public Nullable<System.DateTime> FechaSegundoVencimiento { get; set; }

    public byte[] Adjunto { get; set; }

    public Nullable<int> IdComprobante { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Activos> Activos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asientos> Asientos { get; set; }

    public virtual Categorias Categorias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Jurisdicciones> Jurisdicciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PagosDetalle> PagosDetalle { get; set; }

    public virtual Personas Personas { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
