
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ComunicacionesAFIP
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ComunicacionesAFIP()
    {

        this.ComunicacionesAFIPAdjuntos = new HashSet<ComunicacionesAFIPAdjuntos>();

    }


    public long IdComunicacion { get; set; }

    public string CuitDestinatario { get; set; }

    public string FechaPublicacion { get; set; }

    public string fechaVencimiento { get; set; }

    public Nullable<long> SistemaPublicador { get; set; }

    public string sistemaPublicadorDesc { get; set; }

    public Nullable<int> Estado { get; set; }

    public string EstadoDesc { get; set; }

    public string Asunto { get; set; }

    public Nullable<int> Prioridad { get; set; }

    public string PrioridadDesc { get; set; }

    public Nullable<int> TieneAdjunto { get; set; }

    public Nullable<int> Visto { get; set; }

    public int IdUsuario { get; set; }

    public System.DateTime FechaRegistro { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComunicacionesAFIPAdjuntos> ComunicacionesAFIPAdjuntos { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
