
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ComunicacionesAFIPAdjuntos
{

    public int IdComunicacionAFIPAdjunto { get; set; }

    public long IdComunicacion { get; set; }

    public string NombreArchivo { get; set; }

    public int Comprimido { get; set; }

    public int Firmado { get; set; }

    public int Encriptado { get; set; }

    public int Procesado { get; set; }

    public int Publico { get; set; }

    public string MD5 { get; set; }

    public long Tamaño { get; set; }

    public byte[] Contenido { get; set; }



    public virtual ComunicacionesAFIP ComunicacionesAFIP { get; set; }

}

}
