
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Conceptos_Lote
{

    public int Id_Lote { get; set; }

    public Nullable<int> NroLote { get; set; }

    public Nullable<int> Id_Usuario { get; set; }

    public Nullable<System.DateTime> FechaLote { get; set; }

}

}
