
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Conceptos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Conceptos()
    {

        this.PreciosConceptos = new HashSet<PreciosConceptos>();

        this.PresupuestoDetalle = new HashSet<PresupuestoDetalle>();

        this.StockAuditoria = new HashSet<StockAuditoria>();

        this.ComprobantesDetalle = new HashSet<ComprobantesDetalle>();

    }


    public int IDConcepto { get; set; }

    public int IDUsuario { get; set; }

    public string Nombre { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public decimal Stock { get; set; }

    public decimal StockFisico { get; set; }

    public decimal PrecioUnitario { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public decimal Iva { get; set; }

    public string Tipo { get; set; }

    public string Foto { get; set; }

    public Nullable<decimal> CostoInterno { get; set; }

    public Nullable<decimal> StockMinimo { get; set; }

    public Nullable<int> IDPersona { get; set; }

    public string CodigoIva { get; set; }

    public Nullable<int> IdConceptoVinculado { get; set; }

    public decimal PorcentajeRentabilidad { get; set; }

    public int UnidadDeMedida { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }

    public Nullable<int> IdTipoIVA { get; set; }



    public virtual Personas Personas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PreciosConceptos> PreciosConceptos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PresupuestoDetalle> PresupuestoDetalle { get; set; }

    public virtual TipoIVA TipoIVA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockAuditoria> StockAuditoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComprobantesDetalle> ComprobantesDetalle { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
