
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ConfiguracionPlanDeCuenta
{

    public int IDConfiguracionPlanDeCuenta { get; set; }

    public int IDUsuario { get; set; }

    public int IDCtaIIBB { get; set; }

    public int IDCtaPercepcionIVA { get; set; }

    public int IDCtaProveedores { get; set; }

    public int IDCtaIVACreditoFiscal { get; set; }

    public int IDCtaValoresADepositar { get; set; }

    public int IDCtaCaja { get; set; }

    public int IDCtaBancos { get; set; }

    public int IDctaRetIVA { get; set; }

    public int IDctaRetIIBB { get; set; }

    public int IDctaRetGanancias { get; set; }

    public int IDCtaDeudoresPorVentas { get; set; }

    public int IDCtaIVADebitoFiscal { get; set; }

    public int IDCtaRetSUSS { get; set; }

    public int IDCtaResultadoEjercicio { get; set; }

    public int IDCtaGastosBancarios { get; set; }

    public string CtasFiltroVentas { get; set; }

    public string CtasFiltroCompras { get; set; }

    public int IDCtaConceptosNoGravadosxCompras { get; set; }

    public int IDCtaConceptosNoGravadosxVentas { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
