
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class DatosAFIPPersonas
{

    public int IDDatosAFIPPersona { get; set; }

    public int IdUsuario { get; set; }

    public string CUIT { get; set; }

    public System.DateTime Fecha { get; set; }

    public string RazonSocial { get; set; }

    public string CategoriaImpositiva { get; set; }

    public string Personeria { get; set; }

    public Nullable<System.DateTime> FechaContratoSocial { get; set; }

    public Nullable<int> DomicilioFiscalIdProvincia { get; set; }

    public string DomicilioFiscalProvincia { get; set; }

    public string DomicilioFiscalCiudad { get; set; }

    public string DomicilioFiscalDomicilio { get; set; }

    public string DomicilioFiscalCP { get; set; }

    public string CategoriaMonotributoDescripcionCategoria { get; set; }

    public string CategoriaMonotributoIdCategoria { get; set; }

    public string CategoriaMonotributoIdImpuesto { get; set; }

    public string CategoriaMonotributoPeriodo { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
