
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Empleados
{

    public int IDEmpleados { get; set; }

    public int IDUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CUIT { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public Nullable<int> NroLegajo { get; set; }

    public string Domicilio { get; set; }

    public string PisoDepto { get; set; }

    public int IDProvincia { get; set; }

    public int IDCiudad { get; set; }

    public string ObraSocial { get; set; }

    public string Sueldo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public Nullable<System.DateTime> FechaBaja { get; set; }

    public string ContactoEmergencia { get; set; }

    public string Email { get; set; }

    public string Foto { get; set; }



    public virtual Ciudades Ciudades { get; set; }

    public virtual Provincias Provincias { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
