
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class GastosBancarios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GastosBancarios()
    {

        this.Asientos = new HashSet<Asientos>();

    }


    public int IDGastosBancarios { get; set; }

    public int IDUsuario { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public int IDBanco { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Concepto { get; set; }

    public decimal Importe { get; set; }

    public decimal IVA { get; set; }

    public decimal Debito { get; set; }

    public decimal Credito { get; set; }

    public decimal IIBB { get; set; }

    public decimal Otros { get; set; }

    public decimal Importe21 { get; set; }

    public decimal CreditoComputable { get; set; }

    public decimal PercepcionIVA { get; set; }

    public decimal SIRCREB { get; set; }

    public decimal Importe10 { get; set; }

    public Nullable<decimal> TotalImportes { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asientos> Asientos { get; set; }

    public virtual Bancos Bancos { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
