
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LicenciaTemp
{

    public int IdLicenciaTemp { get; set; }

    public long CUIT { get; set; }

    public string Email { get; set; }

    public string Vigencia { get; set; }

    public string Clave { get; set; }

    public string Modulo1_Nombre { get; set; }

    public string Modulo1_Version { get; set; }

    public string Modulo1_UrlInstalador32 { get; set; }

    public string Modulo1_UrlInstalador64 { get; set; }

    public string Modulo2_Nombre { get; set; }

    public string Modulo2_Version { get; set; }

    public string Modulo2_UrlInstalador32 { get; set; }

    public string Modulo2_UrlInstalador64 { get; set; }

    public string Modulo3_Nombre { get; set; }

    public string Modulo3_Version { get; set; }

    public string Modulo3_UrlInstalador32 { get; set; }

    public string Modulo3_UrlInstalador64 { get; set; }

    public string Modulo4_Nombre { get; set; }

    public string Modulo4_Version { get; set; }

    public string Modulo4_UrlInstalador32 { get; set; }

    public string Modulo4_UrlInstalador64 { get; set; }

    public string Modulo5_Nombre { get; set; }

    public string Modulo5_Version { get; set; }

    public string Modulo5_UrlInstalador32 { get; set; }

    public string Modulo5_UrlInstalador64 { get; set; }

}

}
