
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ListaPrecios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ListaPrecios()
    {

        this.PreciosConceptos = new HashSet<PreciosConceptos>();

        this.Personas = new HashSet<Personas>();

    }


    public int IDListaPrecio { get; set; }

    public int IDUsuario { get; set; }

    public string Nombre { get; set; }

    public string Observaciones { get; set; }

    public bool Activa { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PreciosConceptos> PreciosConceptos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personas> Personas { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
