
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LoginUsuarios
{

    public int IDLogin { get; set; }

    public Nullable<int> IDUsuario { get; set; }

    public Nullable<int> IDUsuarioAdicional { get; set; }

    public System.DateTime FechaLogin { get; set; }

    public string IPCliente { get; set; }

    public string EmailLogin { get; set; }

    public string Observacion { get; set; }



    public virtual UsuariosAdicionales UsuariosAdicionales { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
