
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LogServicios
{

    public int IDLogServicio { get; set; }

    public string Entidad { get; set; }

    public string Url { get; set; }

    public string Nombre { get; set; }

    public string Mensaje { get; set; }

    public System.DateTime FechaEmision { get; set; }

    public int IdUsuario { get; set; }

    public int Envio { get; set; }

    public string Respuesta { get; set; }

    public Nullable<bool> RespuestaExitosa { get; set; }

    public Nullable<System.DateTime> FechaRespuesta { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
