
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class MovimientoDeFondos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MovimientoDeFondos()
    {

        this.Asientos = new HashSet<Asientos>();

    }


    public int IDMovimientoDeFondo { get; set; }

    public int IDUsuario { get; set; }

    public Nullable<int> IDBancoOrigen { get; set; }

    public Nullable<int> IDBancoDestino { get; set; }

    public string Origen { get; set; }

    public string Destino { get; set; }

    public string Foto { get; set; }

    public System.DateTime FechaDeAlta { get; set; }

    public System.DateTime FechaMovimiento { get; set; }

    public decimal Importe { get; set; }

    public string Observaciones { get; set; }

    public string CajaOrigen { get; set; }

    public string CajaDestino { get; set; }

    public string EstadoCaja { get; set; }

    public System.DateTime EstadoCajaFecha { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asientos> Asientos { get; set; }

    public virtual Bancos Bancos { get; set; }

    public virtual Bancos Bancos1 { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
