
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ObservacionesUsuario
{

    public int IDObservacionUsuario { get; set; }

    public int IDUsuario { get; set; }

    public string Observacion { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Proyecto { get; set; }

    public bool TieneError { get; set; }

    public string MensajeError { get; set; }

    public string TipoNotificacion { get; set; }



    public virtual Usuarios Usuarios { get; set; }

}

}
