
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PersonasTemp
{

    public int IDPersona { get; set; }

    public int IDUsuario { get; set; }

    public string RazonSocial { get; set; }

    public string NombreFantasia { get; set; }

    public string Email { get; set; }

    public string TipoDocumento { get; set; }

    public string NroDocumento { get; set; }

    public string CondicionIva { get; set; }

    public int Provincia { get; set; }

    public Nullable<int> Ciudad { get; set; }

    public string Domicilio { get; set; }

    public string Web { get; set; }

    public string Tipo { get; set; }

    public string Personeria { get; set; }

}

}
