
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PlanesPagos
{

    public int IDPlanesPagos { get; set; }

    public int IDUsuario { get; set; }

    public int IDPlan { get; set; }

    public System.DateTime FechaDeAlta { get; set; }

    public System.DateTime FechaDePago { get; set; }

    public Nullable<System.DateTime> FechaInicioPlan { get; set; }

    public Nullable<System.DateTime> FechaFinPlan { get; set; }

    public decimal ImportePagado { get; set; }

    public string FormaDePago { get; set; }

    public bool PagoAnual { get; set; }

    public string Foto { get; set; }

    public string NroReferencia { get; set; }

    public string Estado { get; set; }

    public Nullable<int> IDComprobante { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    public virtual Planes Planes { get; set; }

    public virtual Comprobantes Comprobantes { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
