
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PlanDeCuentaBase
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PlanDeCuentaBase()
    {

        this.PlanDeCuentaBase1 = new HashSet<PlanDeCuentaBase>();

    }


    public int IDPlanDeCuentaBase { get; set; }

    public string Nombre { get; set; }

    public string Codigo { get; set; }

    public Nullable<int> IDPadre { get; set; }

    public bool AdminiteAsientoManual { get; set; }

    public string TipoDeCuenta { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PlanDeCuentaBase> PlanDeCuentaBase1 { get; set; }

    public virtual PlanDeCuentaBase PlanDeCuentaBase2 { get; set; }

}

}
