
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PreciosConceptos
{

    public int IDPrecioConcepto { get; set; }

    public int IDListaPrecios { get; set; }

    public int IDConceptos { get; set; }

    public decimal Precio { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    public virtual ListaPrecios ListaPrecios { get; set; }

    public virtual Conceptos Conceptos { get; set; }

}

}
