
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Presupuestos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Presupuestos()
    {

        this.PresupuestoDetalle = new HashSet<PresupuestoDetalle>();

    }


    public int IDPresupuesto { get; set; }

    public int IDPersona { get; set; }

    public int IDUsuario { get; set; }

    public int Numero { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaValidez { get; set; }

    public string FormaDePago { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public decimal ImporteTotalNeto { get; set; }

    public decimal ImporteTotalBruto { get; set; }

    public string Vendedor { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }



    public virtual Personas Personas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PresupuestoDetalle> PresupuestoDetalle { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
