//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptCuentasAPagar
    {
        public System.DateTime FechaAlta { get; set; }
        public int IDUsuario { get; set; }
        public int IDPersona { get; set; }
        public string TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string NroFactura { get; set; }
        public string Proveedor { get; set; }
        public string CondicionIVA { get; set; }
        public decimal Iva { get; set; }
        public decimal Importe { get; set; }
        public decimal Total { get; set; }
        public decimal TotalAbonado { get; set; }
    }
}
