
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptChequesAcciones
{

    public Nullable<int> IDPlan { get; set; }

    public int IDCheque { get; set; }

    public int IDUsuario { get; set; }

    public string Email { get; set; }

    public string EmailAlertas { get; set; }

    public string RazonSocial { get; set; }

    public string Banco { get; set; }

    public string Numero { get; set; }

    public System.DateTime FechaEmision { get; set; }

    public decimal Importe { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public string Estado { get; set; }

    public string Emisor { get; set; }

    public string Observaciones { get; set; }

    public Nullable<System.DateTime> FechaCobro { get; set; }

    public Nullable<System.DateTime> FechaVencimiento { get; set; }

    public string Foto { get; set; }

    public bool EsPropio { get; set; }

    public string Accion { get; set; }

    public Nullable<decimal> Resto { get; set; }

    public Nullable<int> IdPersona { get; set; }

    public string Cliente { get; set; }

    public string CUIT { get; set; }

    public bool EsPropioEmpresa { get; set; }

}

}
