
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptEstadoResultadoView
{

    public System.DateTime Fecha { get; set; }

    public string TipoDeAsiento { get; set; }

    public string Cuenta { get; set; }

    public int IDPlanDeCuenta { get; set; }

    public Nullable<decimal> Importe { get; set; }

    public int IDUsuario { get; set; }

}

}
