
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptIvaCompras
{

    public System.DateTime Fecha { get; set; }

    public string Tipo { get; set; }

    public string Factura { get; set; }

    public string RazonSocial { get; set; }

    public string CUIT { get; set; }

    public int IDUsuario { get; set; }

    public int IDPersona { get; set; }

    public string CondicionIVA { get; set; }

    public decimal Importe2 { get; set; }

    public decimal Importe5 { get; set; }

    public decimal Importe10 { get; set; }

    public decimal Importe21 { get; set; }

    public decimal Importe27 { get; set; }

    public decimal ImporteMon { get; set; }

    public Nullable<decimal> TotalImporte { get; set; }

    public decimal Iva { get; set; }

    public decimal NoGravado { get; set; }

    public decimal Percepciones { get; set; }

    public decimal ImpInterno { get; set; }

    public decimal ImpMunicipal { get; set; }

    public decimal ImpNacional { get; set; }

    public decimal PercepcionIVA { get; set; }

    public decimal IIBB { get; set; }

    public decimal Otros { get; set; }

    public string Rubro { get; set; }

    public decimal Exento { get; set; }

}

}
