
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptIvaVentas
{

    public System.DateTime Fecha { get; set; }

    public string CUIT { get; set; }

    public int IDUsuario { get; set; }

    public int IDPersona { get; set; }

    public string RazonSocial { get; set; }

    public string CondicionIva { get; set; }

    public string Tipo { get; set; }

    public int IDPuntoVenta { get; set; }

    public int PuntoVenta { get; set; }

    public int Factura { get; set; }

    public decimal ImporteBruto { get; set; }

    public Nullable<int> IdActividad { get; set; }

    public string Actividad { get; set; }

    public decimal Iva { get; set; }

    public decimal ImporteNeto { get; set; }

    public Nullable<decimal> IVA2 { get; set; }

    public Nullable<decimal> IVA5 { get; set; }

    public Nullable<decimal> IVA10 { get; set; }

    public Nullable<decimal> IVA21 { get; set; }

    public Nullable<decimal> IVA27 { get; set; }

}

}
