
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptRankingConceptos
{

    public System.DateTime Fecha { get; set; }

    public int IDUsuario { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string Tipo { get; set; }

    public string Estado { get; set; }

    public string tipoFC { get; set; }

    public int Cantidad { get; set; }

    public decimal Iva { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal Bonificacion { get; set; }

    public Nullable<decimal> Importe { get; set; }

}

}
