
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptRankingClientes
{

    public System.DateTime Fecha { get; set; }

    public string CUIT { get; set; }

    public int IDUsuario { get; set; }

    public int IDPersona { get; set; }

    public string Provincia { get; set; }

    public string Ciudad { get; set; }

    public int IDProvincia { get; set; }

    public int IDCiudad { get; set; }

    public string RazonSocial { get; set; }

    public string CondicionIVA { get; set; }

    public string Tipo { get; set; }

    public int Cantidad { get; set; }

    public decimal Importe { get; set; }

}

}
