
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RptSaldosCc
{

    public int IDPersona { get; set; }

    public int IDUsuario { get; set; }

    public string RazonSocial { get; set; }

    public decimal SaldoCliente { get; set; }

    public decimal SaldoProveedor { get; set; }

}

}
