
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TicketsAfip
{

    public Nullable<decimal> CUIT { get; set; }

    public System.DateTime Creado { get; set; }

    public string Servicio { get; set; }

    public string Firma { get; set; }

    public string Token { get; set; }

    public string UniqueID { get; set; }

    public System.DateTime Vencimiento { get; set; }

    public string Modo { get; set; }

}

}
