
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TrackingHoras
{

    public int IDTrackingHoras { get; set; }

    public int IDUsuario { get; set; }

    public int IDPersona { get; set; }

    public System.DateTime Fecha { get; set; }

    public int Horas { get; set; }

    public string Tarea { get; set; }

    public string Observaciones { get; set; }

    public string Estado { get; set; }

    public Nullable<int> IDUsuarioAdicional { get; set; }



    public virtual UsuariosAdicionales UsuariosAdicionales { get; set; }

    public virtual Personas Personas { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
