
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class UsuariosAdicionales
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UsuariosAdicionales()
    {

        this.LoginUsuarios = new HashSet<LoginUsuarios>();

        this.TrackingHoras = new HashSet<TrackingHoras>();

        this.UsuariosEmpresa = new HashSet<UsuariosEmpresa>();

        this.Roles = new HashSet<Roles>();

    }


    public int IDUsuarioAdicional { get; set; }

    public int IDUsuario { get; set; }

    public string Email { get; set; }

    public string Pwd { get; set; }

    public bool Activo { get; set; }

    public string Tipo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public bool EstaBloqueado { get; set; }

    public int CantIntentos { get; set; }

    public bool EsVendedor { get; set; }

    public decimal PorcentajeComision { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoginUsuarios> LoginUsuarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrackingHoras> TrackingHoras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsuariosEmpresa> UsuariosEmpresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Roles> Roles { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
