
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class UsuariosView
{

    public int IDUsuarioAdicional { get; set; }

    public string Tipo { get; set; }

    public int IDUsuario { get; set; }

    public Nullable<int> IDEstudio { get; set; }

    public string RazonSocial { get; set; }

    public string Personeria { get; set; }

    public string Email { get; set; }

    public string Pwd { get; set; }

    public string CUIT { get; set; }

    public string IIBB { get; set; }

    public Nullable<System.DateTime> FechaInicioActividades { get; set; }

    public string CondicionIva { get; set; }

    public int IDProvincia { get; set; }

    public int IDCiudad { get; set; }

    public string Domicilio { get; set; }

    public string PisoDepto { get; set; }

    public string CodigoPostal { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string EmailAlertas { get; set; }

    public string Logo { get; set; }

    public string Theme { get; set; }

    public int IDPlan { get; set; }

    public bool Activo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaUltLogin { get; set; }

    public string Contacto { get; set; }

    public bool TieneFacturaElectronica { get; set; }

    public string TemplateFc { get; set; }

    public string Pais { get; set; }

    public bool SetupRealizado { get; set; }

    public bool UsaProd { get; set; }

    public bool CorreoPortal { get; set; }

    public bool PortalClientes { get; set; }

    public Nullable<int> IDUsuarioPadre { get; set; }

    public string ApiKey { get; set; }

    public string CodigoPromo { get; set; }

    public Nullable<bool> EsAgentePercepcionIVA { get; set; }

    public Nullable<bool> EsAgentePercepcionIIBB { get; set; }

    public Nullable<bool> EsAgenteRetencion { get; set; }

    public System.DateTime FechaFinPlan { get; set; }

    public bool UsaFechaFinPlan { get; set; }

    public string Observaciones { get; set; }

    public int CantidadEmpresas { get; set; }

    public Nullable<bool> ExentoIIBB { get; set; }

    public bool UsaPrecioFinalConIVA { get; set; }

    public Nullable<System.DateTime> FechaBaja { get; set; }

    public string Provincia { get; set; }

    public string Ciudad { get; set; }

    public bool EstaBloqueado { get; set; }

    public bool EnvioAutomaticoComprobante { get; set; }

    public bool EnvioAutomaticoRecibo { get; set; }

    public string IDJurisdiccion { get; set; }

    public bool Escontador { get; set; }

    public bool UsaPlanCorporativo { get; set; }

    public bool PedidoDeVenta { get; set; }

    public string TiendaNubeIdTienda { get; set; }

    public string TiendaNubeToken { get; set; }

    public string CUITAfip { get; set; }

    public decimal PorcentajeCompra { get; set; }

    public decimal PorcentajeRentabilidad { get; set; }

    public Nullable<bool> EsAgenteRetencionGanancia { get; set; }

    public bool ParaPDVSolicitarCompletarContacto { get; set; }

    public bool EsVendedor { get; set; }

    public decimal PorcentajeComision { get; set; }

    public bool FacturaSoloContraEntrega { get; set; }

    public bool UsaCantidadConDecimales { get; set; }

    public string CBU { get; set; }

}

}
