
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class UsuariosPlanesView
{

    public int IDUsuario { get; set; }

    public string RazonSocial { get; set; }

    public string CondicionIva { get; set; }

    public string CUIT { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string EmailAlertas { get; set; }

    public bool SetupRealizado { get; set; }

    public Nullable<int> IDPlan { get; set; }

    public string PlanActual { get; set; }

    public string Estado { get; set; }

    public Nullable<System.DateTime> FechaFinPlan { get; set; }

    public Nullable<int> AntiguedadMeses { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaUltLogin { get; set; }

    public bool Activo { get; set; }

}

}
