
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Usuarios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuarios()
    {

        this.Abonos = new HashSet<Abonos>();

        this.AccesoFormularioUsuario = new HashSet<AccesoFormularioUsuario>();

        this.Actividad = new HashSet<Actividad>();

        this.Alertas = new HashSet<Alertas>();

        this.AlertasGeneradas = new HashSet<AlertasGeneradas>();

        this.Asientos = new HashSet<Asientos>();

        this.AuditoriaDeCambio = new HashSet<AuditoriaDeCambio>();

        this.AuthenticationToken = new HashSet<AuthenticationToken>();

        this.AvisosVencimiento = new HashSet<AvisosVencimiento>();

        this.Bancos = new HashSet<Bancos>();

        this.BancosPlanDeCuenta = new HashSet<BancosPlanDeCuenta>();

        this.Caja = new HashSet<Caja>();

        this.Categorias = new HashSet<Categorias>();

        this.ChequeAccion = new HashSet<ChequeAccion>();

        this.Cheques = new HashSet<Cheques>();

        this.Cobranzas = new HashSet<Cobranzas>();

        this.Compras = new HashSet<Compras>();

        this.Comprobantes = new HashSet<Comprobantes>();

        this.ComprobantesEnviados = new HashSet<ComprobantesEnviados>();

        this.ComunicacionesAFIP = new HashSet<ComunicacionesAFIP>();

        this.Conceptos = new HashSet<Conceptos>();

        this.ConceptosCaja = new HashSet<ConceptosCaja>();

        this.ConfiguracionPlanDeCuenta = new HashSet<ConfiguracionPlanDeCuenta>();

        this.DatosAFIPPersonas = new HashSet<DatosAFIPPersonas>();

        this.Empleados = new HashSet<Empleados>();

        this.GastosBancarios = new HashSet<GastosBancarios>();

        this.GastosGenerales = new HashSet<GastosGenerales>();

        this.LiquidoProductoMargenes = new HashSet<LiquidoProductoMargenes>();

        this.ListaPrecios = new HashSet<ListaPrecios>();

        this.LoginUsuarios = new HashSet<LoginUsuarios>();

        this.LogServicios = new HashSet<LogServicios>();

        this.MovimientoDeFondos = new HashSet<MovimientoDeFondos>();

        this.ObservacionesUsuario = new HashSet<ObservacionesUsuario>();

        this.Pagos = new HashSet<Pagos>();

        this.Personas = new HashSet<Personas>();

        this.PlanDeCuentas = new HashSet<PlanDeCuentas>();

        this.PlanesPagos = new HashSet<PlanesPagos>();

        this.Presupuestos = new HashSet<Presupuestos>();

        this.PuntosDeVenta = new HashSet<PuntosDeVenta>();

        this.RemitoComprobanteMargenes = new HashSet<RemitoComprobanteMargenes>();

        this.StockAuditoria = new HashSet<StockAuditoria>();

        this.TrackingHoras = new HashSet<TrackingHoras>();

        this.Transporte = new HashSet<Transporte>();

        this.TransportePersona = new HashSet<TransportePersona>();

        this.ConceptosTmp = new HashSet<ConceptosTmp>();

        this.UsuariosAdicionales = new HashSet<UsuariosAdicionales>();

        this.UsuariosEmpresa = new HashSet<UsuariosEmpresa>();

    }


    public int IDUsuario { get; set; }

    public Nullable<int> IDEstudio { get; set; }

    public string RazonSocial { get; set; }

    public string Personeria { get; set; }

    public string Email { get; set; }

    public string Pwd { get; set; }

    public string CUIT { get; set; }

    public string IIBB { get; set; }

    public Nullable<System.DateTime> FechaInicioActividades { get; set; }

    public string CondicionIva { get; set; }

    public int IDProvincia { get; set; }

    public int IDCiudad { get; set; }

    public string Domicilio { get; set; }

    public string PisoDepto { get; set; }

    public string CodigoPostal { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string EmailAlertas { get; set; }

    public string Logo { get; set; }

    public string Theme { get; set; }

    public int IDPlan { get; set; }

    public bool Activo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaUltLogin { get; set; }

    public string Contacto { get; set; }

    public bool TieneFacturaElectronica { get; set; }

    public string TemplateFc { get; set; }

    public string Pais { get; set; }

    public bool SetupRealizado { get; set; }

    public bool UsaProd { get; set; }

    public bool CorreoPortal { get; set; }

    public bool PortalClientes { get; set; }

    public Nullable<int> IDUsuarioPadre { get; set; }

    public string ApiKey { get; set; }

    public string CodigoPromo { get; set; }

    public Nullable<bool> EsAgentePercepcionIVA { get; set; }

    public Nullable<bool> EsAgentePercepcionIIBB { get; set; }

    public Nullable<bool> EsAgenteRetencion { get; set; }

    public Nullable<bool> EsAgenteRetencionGanancia { get; set; }

    public string MercadoPagoClientID { get; set; }

    public string MercadoPagoClientSecret { get; set; }

    public System.DateTime FechaFinPlan { get; set; }

    public bool UsaFechaFinPlan { get; set; }

    public string Observaciones { get; set; }

    public int CantidadEmpresas { get; set; }

    public Nullable<bool> ExentoIIBB { get; set; }

    public bool UsaPrecioFinalConIVA { get; set; }

    public Nullable<System.DateTime> FechaBaja { get; set; }

    public string MotivoBaja { get; set; }

    public Nullable<System.DateTime> FechaCierreContable { get; set; }

    public bool EstaBloqueado { get; set; }

    public int CantIntentos { get; set; }

    public bool EnvioAutomaticoComprobante { get; set; }

    public bool EnvioAutomaticoRecibo { get; set; }

    public string IDJurisdiccion { get; set; }

    public bool EsContador { get; set; }

    public bool UsaPlanCorporativo { get; set; }

    public bool PedidoDeVenta { get; set; }

    public string TiendaNubeIdTienda { get; set; }

    public string TiendaNubeToken { get; set; }

    public string CUITAfip { get; set; }

    public decimal PorcentajeCompra { get; set; }

    public decimal PorcentajeRentabilidad { get; set; }

    public int Moneda { get; set; }

    public string AtributoDeSeguridad { get; set; }

    public bool ParaPDVSolicitarCompletarContacto { get; set; }

    public bool EsVendedor { get; set; }

    public decimal PorcentajeComision { get; set; }

    public bool FacturaSoloContraEntrega { get; set; }

    public bool UsaCantidadConDecimales { get; set; }

    public string CBU { get; set; }

    public string TextoFinalFactura { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Abonos> Abonos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AccesoFormularioUsuario> AccesoFormularioUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Actividad> Actividad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Alertas> Alertas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AlertasGeneradas> AlertasGeneradas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asientos> Asientos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AuditoriaDeCambio> AuditoriaDeCambio { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AuthenticationToken> AuthenticationToken { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AvisosVencimiento> AvisosVencimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bancos> Bancos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BancosPlanDeCuenta> BancosPlanDeCuenta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Caja> Caja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Categorias> Categorias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChequeAccion> ChequeAccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cheques> Cheques { get; set; }

    public virtual Ciudades Ciudades { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cobranzas> Cobranzas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Compras> Compras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comprobantes> Comprobantes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComprobantesEnviados> ComprobantesEnviados { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComunicacionesAFIP> ComunicacionesAFIP { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Conceptos> Conceptos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConceptosCaja> ConceptosCaja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfiguracionPlanDeCuenta> ConfiguracionPlanDeCuenta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DatosAFIPPersonas> DatosAFIPPersonas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empleados> Empleados { get; set; }

    public virtual Estudios Estudios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GastosBancarios> GastosBancarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GastosGenerales> GastosGenerales { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LiquidoProductoMargenes> LiquidoProductoMargenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListaPrecios> ListaPrecios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoginUsuarios> LoginUsuarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LogServicios> LogServicios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MovimientoDeFondos> MovimientoDeFondos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ObservacionesUsuario> ObservacionesUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pagos> Pagos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personas> Personas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PlanDeCuentas> PlanDeCuentas { get; set; }

    public virtual Planes Planes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PlanesPagos> PlanesPagos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Presupuestos> Presupuestos { get; set; }

    public virtual Provincias Provincias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PuntosDeVenta> PuntosDeVenta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RemitoComprobanteMargenes> RemitoComprobanteMargenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockAuditoria> StockAuditoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrackingHoras> TrackingHoras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transporte> Transporte { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransportePersona> TransportePersona { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConceptosTmp> ConceptosTmp { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsuariosAdicionales> UsuariosAdicionales { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsuariosEmpresa> UsuariosEmpresa { get; set; }

}

}
