
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vCuadroResumenOriginal
{

    public int IDUsuario { get; set; }

    public int IDPersona { get; set; }

    public string RazonSocial { get; set; }

    public string periodo { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<decimal> Ventas { get; set; }

    public Nullable<decimal> ConEntrega { get; set; }

    public Nullable<decimal> SinEntrega { get; set; }

    public Nullable<decimal> Factura { get; set; }

    public Nullable<decimal> ConCAE { get; set; }

    public Nullable<decimal> SinCAE { get; set; }

    public Nullable<decimal> IVA { get; set; }

    public Nullable<decimal> Cobranza { get; set; }

    public Nullable<decimal> Saldo { get; set; }

}

}
