//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientoPlanes
    {
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string Nombre { get; set; }
        public int IDPlanesPagos { get; set; }
        public int IDUsuario { get; set; }
        public int IDPlan { get; set; }
        public System.DateTime FechaDeAlta { get; set; }
        public System.DateTime FechaDePago { get; set; }
        public decimal ImportePagado { get; set; }
        public string FormaDePago { get; set; }
        public bool PagoAnual { get; set; }
        public string Foto { get; set; }
        public string NroReferencia { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public string Estado { get; set; }
    }
}
