
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vLogServicios
{

    public int IDLogServicio { get; set; }

    public string Entidad { get; set; }

    public string Url { get; set; }

    public string Nombre { get; set; }

    public string Mensaje { get; set; }

    public string FechaEmision { get; set; }

    public string CUIT { get; set; }

    public string RazonSocial { get; set; }

    public string Envio { get; set; }

    public string Respuesta { get; set; }

    public string RespuestaExitosa { get; set; }

    public string FechaRespuesta { get; set; }

}

}
