
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vMovimientoDeFondos
{

    public int IDMovimientoDeFondo { get; set; }

    public string Origen { get; set; }

    public string Destino { get; set; }

    public System.DateTime FechaMovimiento { get; set; }

    public Nullable<int> IDBancoOrigen { get; set; }

    public string BancoOrigenNombre { get; set; }

    public string BancoOrigenNroCuenta { get; set; }

    public Nullable<int> IDBancoDestino { get; set; }

    public string BancoDestinoNombre { get; set; }

    public string BancoDestinoNroCuenta { get; set; }

    public string Observaciones { get; set; }

    public decimal Importe { get; set; }

    public int IDUsuario { get; set; }

}

}
