
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vPdvProcesados
{

    public int IDComprobante { get; set; }

    public int IDPersona { get; set; }

    public string NombreFantansia { get; set; }

    public string RazonSocial { get; set; }

    public System.DateTime FechaComprobante { get; set; }

    public string Nombre { get; set; }

    public int Numero { get; set; }

    public int Punto { get; set; }

    public decimal ImporteTotalBruto { get; set; }

    public decimal ImporteTotalNeto { get; set; }

    public int IdUsuario { get; set; }

    public Nullable<long> ProcesoCompraAutomatica { get; set; }

}

}
