
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ACHE.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vPdvPendientesDeProcesarDetalle
{

    public int IDComprobante { get; set; }

    public int IDPersona { get; set; }

    public int IDDetalle { get; set; }

    public Nullable<int> IdPersonaConcepto { get; set; }

    public int IdUsuario { get; set; }

}

}
